#!/usr/local/bin/perl -w

#
#     FILE: about.pl
#   AUTHOR: Michael J. Radwin
#    DESCR: Alumni Internet Directory CGI "About" page generation
#      $Id: about,v 6.2 2003/08/25 16:13:56 mradwin Exp mradwin $
#
#   Copyright (c) 2003  Michael J. Radwin
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

BEGIN {
    if ($0 =~ m,(.*[/\\]),) {
	unshift @INC, $1;
    } else {
	unshift @INC, '.';
    }
}
use lib "/home/mradwin/local/share/perl";

use DB_File::Lock;
use aid_util;
use strict;

aid_util::cgi_die('$PATH_INFO Missing', "This URL is bogus.")
    unless defined $ENV{'PATH_INFO'};

$ENV{'PATH_INFO'} =~ s/\+/ /g;
$ENV{'PATH_INFO'} =~ s/%([A-Fa-f0-9]{2})/pack("c",hex($1))/ge;

if ($ENV{'PATH_INFO'} =~ m,/(\d+)$,)
{
    my $id = $1;

    my $dbmfile = aid_util::config('dbmfile');
    die "$dbmfile: $!\n" unless -r $dbmfile;

    my(%DB);
    tie(%DB, 'DB_File::Lock', $dbmfile, O_RDONLY, 0444, $DB_HASH, 'read')
	or die "$dbmfile: $!\n";

    my $val = $DB{$id};

    untie(%DB);

    if (defined $val)
    {
	my %rec = aid_util::db_unpack_rec($id,$val);

	send_about(\%rec);
	close(STDOUT);
	exit(0);
    }
}

$ENV{'PATH_INFO'} =~ s/&/&amp;/g;
$ENV{'PATH_INFO'} =~ s/</&lt;/g;
$ENV{'PATH_INFO'} =~ s/>/&gt;/g;

print "Status: 404 Not Found\015\012";
aid_util::cgi_die('Not Found',
	  "The alumnus " . $ENV{'PATH_INFO'} .
	  " you requested could not be found.\n");

close(STDOUT);
exit(0);

sub send_about
{
    my($recp) = @_;
    my($fullname) = aid_util::inorder_fullname($recp);
    my($html_name) = aid_util::html_entify_str($fullname);

#    print "Last-Modified: ", aid_util::http_date($recp->{'u'}), "\015\012";
    print "Content-Type: text/html\015\012\015\012";

    print aid_util::common_html_hdr(20,$fullname,1,$recp->{'u'});
    print "<p>Below is the current listing for ${html_name}.\n";
    print "Click the modify button below to edit this listing.</p>\n";
    print "
<!-- borrowed from gamelan -->

<p><small>To avoid malicious modification by other people passing
through, we mail the original user about the change (plus the new user
if the e-mail changes). The honor system has worked for us so far;
please don't abuse it and force us to install a password
door.</small></p>

<form method=\"get\" action=\"" . aid_util::config('update_cgi') . "/$recp->{'id'}\">
<input type=\"hidden\" name=\"upd\" value=\"$recp->{'id'}\">
<input type=\"submit\" value=\"Modify $html_name\">
</form>

";
    print "<table border=\"1\" cellpadding=\"6\"><tr><td>";
    print aid_util::verbose_entry($recp,1,1,1);
    print "</td></tr></table>\n&nbsp;";
    print aid_util::common_html_ftr(20,$recp->{'u'});

    1;
}
