#!/usr/local/bin/perl -w

#
#     FILE: about.pl
#   AUTHOR: Michael J. Radwin
#    DESCR: Alumni Directory CGI "About" page generation
#      $Id: about,v 7.1 2006/02/27 16:56:03 mradwin Exp mradwin $
#
# Copyright (c) 2006  Michael J. Radwin.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or
# without modification, are permitted provided that the following
# conditions are met:
#
#  * Redistributions of source code must retain the above
#    copyright notice, this list of conditions and the following
#    disclaimer.
#
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following
#    disclaimer in the documentation and/or other materials
#    provided with the distribution.
#
#  * Neither the name of the High School Alumni Directory
#    nor the names of its contributors may be used to endorse or
#    promote products derived from this software without specific
#    prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

BEGIN {
    if ($0 =~ m,(.*[/\\]),) {
	unshift @INC, $1;
    } else {
	unshift @INC, '.';
    }
}

use strict;
use aid_util;
use DBI ();

aid_util::cgi_die('$PATH_INFO Missing', "This URL is bogus.")
    unless defined $ENV{'PATH_INFO'};

$ENV{'PATH_INFO'} =~ s/\+/ /g;
$ENV{'PATH_INFO'} =~ s/%([A-Fa-f0-9]{2})/pack("c",hex($1))/ge;

if ($ENV{'PATH_INFO'} =~ m,/(\d+)$,)
{
    my $id = $1;

    my $dbh = aid_util::db_connect();
    my $DB = aid_util::load_records($dbh, "AND a.alumnus_id = $id");
    $dbh->disconnect;

    my @recs = values %{$DB};
    if (@recs)
    {
	send_about($recs[0]);
	close(STDOUT);
	exit(0);
    }
}

$ENV{'PATH_INFO'} =~ s/&/&amp;/g;
$ENV{'PATH_INFO'} =~ s/</&lt;/g;
$ENV{'PATH_INFO'} =~ s/>/&gt;/g;

print "Status: 404 Not Found\015\012";
aid_util::cgi_die('Not Found',
	  "The alumnus " . $ENV{'PATH_INFO'} .
	  " you requested could not be found.\n");

close(STDOUT);
exit(0);

sub send_about
{
    my($recp) = @_;
    my($fullname) = aid_util::inorder_fullname($recp);
    my($html_name) = aid_util::html_entify_str($fullname);

#    print "Last-Modified: ", aid_util::http_date($recp->{'u'}), "\015\012";
    print "Content-Type: text/html\015\012\015\012";

    print aid_util::common_html_hdr(20,$fullname,1,$recp->{'u'});
    print "<p>Below is the current listing for ${html_name}.\n";
    print "Click the modify button below to edit this listing.</p>\n";
    print "
<!-- borrowed from gamelan -->

<p><small>To avoid malicious modification by other people passing
through, we mail the original user about the change (plus the new user
if the e-mail changes). The honor system has worked for us so far;
please don't abuse it and force us to install a password
door.</small></p>

<form method=\"get\" action=\"" . aid_util::config('update_cgi') . "/$recp->{'id'}\">
<input type=\"hidden\" name=\"upd\" value=\"$recp->{'id'}\">
<input type=\"submit\" value=\"Modify $html_name\">
</form>

";
    print "<table border=\"1\" cellpadding=\"6\"><tr><td>";
    print aid_util::verbose_entry($recp,1,1,1);
    print "</td></tr></table>\n&nbsp;";
    print aid_util::common_html_ftr(20,$recp->{'u'});

    1;
}
