#!/usr/local/bin/perl

#
#     FILE: mvhsaid.pl
#   AUTHOR: Michael J. Radwin
#    DESCR: MVHS Alumni Internet Directory CGI interface
#      $Id: mvhsaid,v 1.27 1997/09/08 15:53:26 mjr Exp mjr $
#

require 'mv_util.pl';
require 'cgi-lib.pl';

# configuration
$mailprog = &mv_config('mailprog');
$dbfile = &mv_config('wwwdir') . "mvhs.adr";

@required_headers = ('id', 'last', 'first', 'school', 'grad', 'mail');

&ReadParse;

# debugging: what version is installed?
if (defined($in{'version'})) {
    select(STDOUT);  $| = 1;
    print "Content-type: text/plain\n\n";
    print '$Id: mvhsaid,v 1.27 1997/09/08 15:53:26 mjr Exp mjr $', "\n";
    exit(0);
}

# dynamic form here if they set the update flag
if (defined($in{'update'})) {
    if ($in{'update'} =~ /^\d+$/) {
	@db = &mv_create_db($dbfile);
	if (defined($db[$in{'update'}])) {
	    &send_upd_real($db[$in{'update'}],1,0);
	} else {
	    &send_upd_list;
	}
    } else {
	&send_upd_list;
    }
    exit(0);
}

# the undocumented "vcard" feature
if ($in{'vcard'} =~ /^\d+$/) {
    @db = &mv_create_db($dbfile);
    if (defined($db[$in{'vcard'}])) {
	&send_vcard($db[$in{'vcard'}]);
    } else {
	&send_blank_submit;
    }
    exit(0);
}


# the documented "about" feature
if ($in{'about'} =~ /^\d+$/) {
    @db = &mv_create_db($dbfile);
    if (defined($db[$in{'about'}])) {
	&send_about($db[$in{'about'}]);
    } else {
	&send_blank_submit;
    }
    exit(0);
}


# no update flag; did they access this with the right form?
foreach (@required_headers) {
    if (!defined($in{$_})) {
	# wrong form
	&send_blank_submit;
	exit(0);
    }
}


# okay, we've got the right form.  clean up the input.
foreach $key (keys(%in)) {
    $in{$key} =~ s/^\s*//;  # get rid of leading and trailing whitespace
    $in{$key} =~ s/\s*$//;
}

# remove apostropies and leading year from gradyear field
# e.g. '93 -> 93, 1993 -> 93
$in{'grad'} =~ s/^\'(\d+)\s*$/$1/;
$in{'grad'} =~ s/^19(\d+)\s*$/$1/;
$in{'grad'} =~ s/^20(\d+)\s*$/$1/;

#$in{'request'} = (defined($in{'request'})) ? 1 : 0;
$in{'school'} = ($in{'school'} eq 'Other' && $in{'sch_other'} ne '') ? 
    $in{'sch_other'} : $in{'school'};

# did they have the required fields?
if ($in{'school'} eq 'Other') {
    &send_upd_real(";$in{'id'};$in{'request'};$in{'last'};$in{'first'};$in{'married'};$in{'school'};$in{'grad'};$in{'mail'};$in{'homepage'};$in{'location'}",1,1);
    exit(0);
}

foreach (@required_headers) {
    if ($in{$_} =~ /^\s*$/) {
	&send_upd_real(";$in{'id'};$in{'request'};$in{'last'};$in{'first'};$in{'married'};$in{'school'};$in{'grad'};$in{'mail'};$in{'homepage'};$in{'location'}",1,1);
	exit(0);
    }
}

# lowercase the hostname portion of the email address
($mail_user, $mail_addr) = split(/\@/, $in{'mail'});
$mail_addr = 'aol.com' if $mail_addr eq '';
$mail_user = "\L$mail_user\E" if $mail_user eq "\U$mail_user\E";
$in{'mail'} = $mail_user . '@' . "\L$mail_addr\E";


&queue_submission;
exit(0);

sub queue_submission {
    require 'tableheader.pl';

    # a little more cleanup and then update the db.
    $in{'homepage'} = '' if $in{'homepage'} eq 'http://';
    $time = time;
    $date = &today($time);
    $mailto = &mv_config('mailto');
    $mailsubj = &mv_config('mailsubj');
    $mailname = &mv_config('admin_name');

    system("$mailprog -s $mailsubj $mailto <<'EOM'
Dear $mailname,

This was submitted to the MVHS address database:

$time;$in{'id'};$in{'request'};$in{'last'};$in{'first'};$in{'married'};$in{'school'};$in{'grad'};$in{'mail'};$in{'homepage'};$in{'location'}

The kind soul who submitted it was using the web from $ENV{'REMOTE_HOST'}
Their browser is $ENV{'HTTP_USER_AGENT'}

Love,
the mvhsaid cgi-bin script
$date
EOM
");

    select(STDOUT);  $| = 1;
    print "Content-type: text/html\n\n";
    print &common_html_hdr(-1,1);

    print "<br>\n";
    print &tableheader("Your submission is queued", 1, "ffff99", 1);
    print "<p>Thank you!  The following information is queued for submission\n";
    print "in the MVHS Alumni Internet Directory:</p>\n";

    print &about_text(";;$in{'request'};$in{'last'};$in{'first'};$in{'married'};$in{'school'};$in{'grad'};$in{'mail'};$in{'homepage'};$in{'location'}",1,1), "\n";

    print &common_html_ftr(-1);
}


sub bydatakeys { $datakeys[$a] cmp $datakeys[$b] }
sub mv_alpha_db {
    local(@db) = &mv_create_db($_[0]);
    local(@alpha, @fields);
    local($_);

    @datakeys = ();

    foreach (@db) {
	@fields = split(/;/);
	push(@datakeys, "$fields[3];$fields[4]");
    }

    @alpha = @db[sort bydatakeys $[..$#db];
    return @alpha;
}

sub send_blank_submit {
    &send_upd_real(";-1;2;;;;MVHS;;;",0,0);
}

sub send_upd_real {
    local($[) = 0;
    local($rawdata,$interactivep,$blank) = @_;

    select(STDOUT);  $| = 1;
    print "Content-type: text/html\n\n";

    print &common_html_hdr(-1,1);
    print &submit_body($rawdata,$interactivep,$blank);
    print &common_html_ftr(-1);
}

sub send_about {
    require 'tableheader.pl';
     
    local($[) = 0;
    local($_);
    local($time,$id,$req,$last,$first,$married,
	  $school,$year,$email,$homepage,$location) = split(/;/, $_[0]);
    local($fullname) = &inorder_fullname($first,$last,$married);

    select(STDOUT);  $| = 1;
    print "Content-type: text/html\n\n";
    print &common_html_hdr(-1,1);
    print "<br>\n";
    print &tableheader($fullname, 1, "ffff99", 1);
    print "<p>Here is more detailed information about $fullname.  To see\n";
    print "<a href=\"" . &mv_config('cgi_path') . "?vcard=$id\">";
    print "${first}'s vCard</a>,\n";
    print "you must be using Netscape 4 or have the \n";
    print "<a href=\"http://www.nowsoft.com/plugins/about_people.html\">";
    print "About People</a>\n";
    print "plugin installed.  To learn more about vCard, check out the\n";
    print "<a href=\"http://www.imc.org/pdi/\">Internet Mail Consortium</a>'s";
    print " website.\n\n";
    print &about_text($_[0],0,1,1), "\n";
    print &common_html_ftr(-1);
}

sub send_vcard {
    local($[) = 0;
    local($_);
    local($time,$id,$req,$last,$first,$married,
	  $school,$year,$email,$homepage,$location) = split(/;/, $_[0]);

    $long_last  = $last;
    $long_last .= " $married" if $married ne '';

    select(STDOUT);  $| = 1;
    print "Content-type: text/x-vCard\n\n";
    print "Begin:vCard\n";
    print "ORG:$school;";
    if ($year =~ /^\d+$/) {
	print "Class of '$year\n";
    } else {
	print "$year\n";
    }
    print "FN: $first $long_last\n";
    print "N:$last;$first;$married\n";
    print "EMAIL;PREF;INTERNET:$email\n";
    print "ADR:$location\n" if $location ne '';
    print "URL:$homepage\n" if $homepage ne '';
    print "End:vCard\n";
}


sub send_upd_list {
    require 'tableheader.pl';
     
    local($[) = 0;
    local($_);
    local(@db) = &mv_alpha_db($dbfile);
    local($fullname);
    local($time,$req,$id,$last,$first,$married,
	  $school,$year,$email,$homepage,$location);

    local($info_gif) =
	"<img src=\"" . &mv_config('master_path') . "info.gif\" height=12 width=12 hspace=4 border=0 alt=\"[i]\">";
    local($blank_gif) =
	"<img src=\"" . &mv_config('master_path') . "blank.gif\" height=12 width=12 hspace=4 border=0 alt=\"\">";
    local($cgi) = &mv_config('cgi_path');

    select(STDOUT);  $| = 1;
    print "Content-type: text/html\n\n";
    print &common_html_hdr(-1,1);
    print "<br>\n";
    print &tableheader("Update Your Directory Listing", 1, "ffff99", 1);
    print "\n";
    print "<p>Please select an entry to update from the list below.<p>\n";
    print "<pre>";
    print "Name and Graduation Year$blank_gif                  Email\n";
    print "---------------------------------------------------------------------------\n";

    foreach (@db) {
	next if $_ eq '';
	($time,$id,$req,$last,$first,$married,
	 $school,$year,$email,$homepage,$location) = split(/;/);

	$fullname = &fullname($first,$last,$married);
	$affil = &affiliate($year,$school);

	print "<a href=\"$cgi?about=$id\">$info_gif</a>";
	print "<a href=\"", &mv_config('cgi_path'), "?update=$id\">";
	print $fullname;
	print "</a>";
	print $affil;
	print ' ', ' ' x (41 - (length($fullname) + length($affil)));
	print $email;
	print "\n";
    }
    print "</pre>\n\n";
    print &common_html_ftr(-1);
}

sub panic {
    select(STDOUT);  $| = 1;
    print "Content-type: text/plain\n\n";
    print $_[0], "\n";

    exit;
}
