#!/usr/bin/perl -w

#
#     FILE: go.pl
#   AUTHOR: Michael J. Radwin
#    DESCR: Alumni Directory update redirector
#      $Id: go,v 7.4 2010/07/13 23:06:23 mradwin Exp mradwin $
#
# Copyright (c) 2006  Michael J. Radwin.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or
# without modification, are permitted provided that the following
# conditions are met:
#
#  * Redistributions of source code must retain the above
#    copyright notice, this list of conditions and the following
#    disclaimer.
#
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following
#    disclaimer in the documentation and/or other materials
#    provided with the distribution.
#
#  * Neither the name of the High School Alumni Directory
#    nor the names of its contributors may be used to endorse or
#    promote products derived from this software without specific
#    prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

BEGIN {
    if ($0 =~ m,(.*[/\\]),) {
	unshift @INC, $1;
    } else {
	unshift @INC, '.';
    }
}

use strict;
use CGI qw(-no_xhtml);
use CGI::Carp qw(fatalsToBrowser);
use aid_util;
use aid_submit;
use DBI ();

aid_util::cgi_die('$PATH_INFO Missing', "This URL is bogus.")
    unless defined $ENV{'PATH_INFO'};

$ENV{'PATH_INFO'} =~ s/\+/ /g;
$ENV{'PATH_INFO'} =~ s/%([A-Fa-f0-9]{2})/pack("c",hex($1))/ge;

if ($ENV{'PATH_INFO'} =~ m,/(\d+)$,)
{
    my $id = $1;

    my $dbh = aid_util::db_connect();
    $dbh || aid_util::cgi_die("Database Failure", $DBI::errstr);
    my $DB = aid_util::load_records($dbh, "AND a.alumnus_id = $id");
    $dbh->disconnect;

    my @recs = values %{$DB};
    if (@recs)
    {
	my $recp = $recs[0];

	print "Content-Type: text/html\015\012\015\012";

	print aid_util::common_html_hdr(20,
				   'Modify profile for ' .
				   aid_util::inorder_fullname($recp),
				   1,$recp->{'u'});
	print aid_submit::submit_body($recp,'');
	print aid_util::common_html_ftr(20,$recp->{'u'});

	close(STDOUT);
	exit(0);
    }
}

$ENV{'PATH_INFO'} =~ s/&/&amp;/g;
$ENV{'PATH_INFO'} =~ s/</&lt;/g;
$ENV{'PATH_INFO'} =~ s/>/&gt;/g;

print "Status: 404 Not Found\015\012";
aid_util::cgi_die('Not Found',
	  "The alumnus " . $ENV{'PATH_INFO'} .
	  " you requested could not be found.\n");

close(STDOUT);
exit(0);
