#!/usr/local/bin/perl -w

#
#     FILE: remove.pl
#   AUTHOR: Michael J. Radwin
#    DESCR: CGI for removal of e-mail address from staging DB
#      $Id: remove,v 1.9 2001/09/16 16:58:27 mradwin Exp mradwin $
#
#   Copyright (c) 1995-2000  Michael John Radwin
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

$dirname = $0;
$dirname =~ s,/[^/]+$,,;
unshift(@INC, $dirname);

require 'aid_util.pl';
use lib "/pub/m/r/mradwin/private/lib/perl5/site_perl";
use DB_File::Lock;
use CGI;
use CGI::Carp qw(fatalsToBrowser);

CGI::ReadParse();
my($key);
if (defined $in{'k'} && $in{'k'} !~ /^\s*$/)
{
    $key = uc($in{'k'});
}
else
{
    my($q) = $ENV{'QUERY_STRING'};
    $q =~ s/%([A-Fa-f0-9]{2})/pack("c",hex($1))/ge;
    if ($q =~ /^(\w+)$/)
    {
	$key = uc($q);
    }
}

if (defined $key)
{
    my $dbmfile = &aid_config('staging');
    die "$dbmfile: $!\n" unless -r $dbmfile;

    my(%DB);
    tie(%DB, 'DB_File::Lock', $dbmfile, O_CREAT|O_RDWR, 0644, $DB_HASH, 'write')
	or die "$dbmfile: $!\n";

    if (defined $DB{$key} && $DB{$key} =~ /^-?\d+\0/)
    {
	my($val) = $DB{$key};
	my($id,$packed) = split(/\0/, $val, 2);
	%rec = &aid_db_unpack_rec($id,$packed);

	if (defined($in{'confirm'}))
	{
	    $DB{$key} = "r\0";
	    untie(%DB);

	    print "Content-Type: text/html\015\012\015\012";
	    print &aid_common_html_hdr(20,'E-mail address removed',1);

	    $admin = &aid_config('admin_email');
	    print "
<p>The Alumni Internet Directory entry for your e-mail address
<b>$rec{'e'}</b>
was removed sucessfully. We apologize for any
inconvenience this may have caused you.</p>

<p>If you need further assistance, contact
<a href=\"mailto:$admin\">$admin</a>.</p>
";
	}
	elsif (defined($in{'skip'}))
	{
	    untie(%DB);

	    print "Location: http://", 
	    &aid_config('master_srv'), &aid_config('master_path'),
	    "\015\012\015\012";

	    close(STDOUT);
	    exit(0);
	}
	else
	{
	    untie(%DB);

	    print "Content-Type: text/html\015\012\015\012";
	    print &aid_common_html_hdr(20,'Remove user',1);

	    print "
<p>You are about to <b>permanently remove</b> the Alumni Internet
Directory entry which is using the e-mail address of:
<b>$rec{'e'}</b>.
If you did <b>not</b> request to be added to the Alumni Internet
Directory, you should remove this entry.</p>

<p><big>Are you are sure you want to <b>permanently remove</b> this
entry from the Directory?</big></p>

<form method=\"post\" action=\"" . &aid_config('remove_cgi') . "\">
<input type=\"hidden\" name=\"k\" value=\"$key\">
<input type=\"submit\" name=\"confirm\" value=\" YES, Remove `$rec{'e'}' \">
&nbsp;&nbsp;&nbsp;&nbsp;
<input type=\"submit\" name=\"skip\" value=\" NO, Leave `$rec{'e'}' alone \">
</form>
";
	}

	print &aid_common_html_ftr(20);

	close(STDOUT);
	exit(0);
    }
    elsif (defined $DB{$key} && $DB{$key} =~ /^[^\0]*\0$/)
    {
	print "Content-Type: text/html\015\012\015\012";
        print &aid_common_html_hdr(20,'Already removed',1);

	print "<p>The removal code you entered\n",
	    "(<b>$key</b>) has already been processed.</p>\n";

	print &aid_common_html_ftr(20);

	close(STDOUT);
	exit(0);
    }
    else
    {
	untie(%DB);

	print "Content-Type: text/html\015\012\015\012";
        print &aid_common_html_hdr(20,'Remove user',1);

	$key =~ s/&/&amp;/g;
	$key =~ s/</&lt;/g;
	$key =~ s/>/&gt;/g;

	print "<p>Sorry, the verification code you entered\n",
	    "(<b>$key</b>) is invalid.</p>\n";
    }
}
else
{
    print "Content-Type: text/html\015\012\015\012";
    print &aid_common_html_hdr(20,'Remove user',1);
}

print "<p>Please check your e-mail and find the 8-letter
removal code that was sent to you by the ",
&aid_config('short_school'), "
Alumni Robot and enter it below.</p>

<form method=\"get\" action=\"" . &aid_config('remove_cgi') . "\">
<label for=\"k\">Enter 8-letter code:</label>
&nbsp;
<input id=\"k\" type=\"text\" size=\"8\" maxlength=\"8\" name=\"k\" value=\"\">
&nbsp;
<input type=\"submit\" value=\"Submit removal code\">
</form>
";

print &aid_common_html_ftr(20);

close(STDOUT);
exit(0);

