#!/usr/local/bin/perl -w

#
#     FILE: vcard.pl
#   AUTHOR: Michael J. Radwin
#    DESCR: Alumni Internet Directory CGI vCard generation
#      $Id: vcard,v 5.7 2000/05/30 17:26:41 mradwin Exp mradwin $
#
#   Copyright (c) 1995-1999  Michael John Radwin
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

$dirname = $0;
$dirname =~ s,/[^/]+$,,;
unshift(@INC, $dirname);

require 'aid_util.pl';
use DB_File;
use Fcntl qw(:DEFAULT :flock);
use CGI;
use CGI::Carp qw(fatalsToBrowser);

&aid_cgi_die('$PATH_INFO Missing', "This URL is bogus.")
    unless defined $ENV{'PATH_INFO'};

$ENV{'PATH_INFO'} =~ s/\+/ /g;
$ENV{'PATH_INFO'} =~ s/%([A-Fa-f0-9]{2})/pack("c",hex($1))/ge;

if ($ENV{'PATH_INFO'} =~ m,/(\d+)\.vcf$,i ||
    $ENV{'PATH_INFO'} =~ m,/(\d+)/.+\.vcf$,i)
{
    $id = $1;

    $dbmfile = &aid_config('dbmfile');
    die "$dbmfile: $!\n" unless -r $dbmfile;

    my($db) = tie(%DB, 'DB_File', $dbmfile, O_RDONLY, 0444, $DB_File::DB_HASH)
	or die "$dbmfile: $!\n";

    my($fd) = $db->fd;
    open(DB_FH, "<&=$fd") || die "dup $!";

    unless (flock (DB_FH, LOCK_SH | LOCK_NB)) {
	unless (flock (DB_FH, LOCK_SH)) { die "flock: $!" }
    }

    if (defined $DB{$id})
    {
	$val = $DB{$id};

	flock(DB_FH, LOCK_UN);
	undef $db;
	untie(%DB);
	close(DB_FH);

	%rec = &aid_db_unpack_rec($id,$val);

	print "Last-Modified: ", &aid_http_date($rec{'u'}), "\015\012";
	print "Content-Type: text/x-vcard\015\012\015\012";
	print &aid_vcard_text(*rec);

	close(STDOUT);
	exit(0);
    }
    else
    {
	flock(DB_FH, LOCK_UN);
	undef $db;
	untie(%DB);
	close(DB_FH);
    }
}

$ENV{'PATH_INFO'} =~ s/&/&amp;/g;
$ENV{'PATH_INFO'} =~ s/</&lt;/g;
$ENV{'PATH_INFO'} =~ s/>/&gt;/g;

print "Status: 404 Not Found\015\012";
&aid_cgi_die('Not Found',
	  "The vCard " . $ENV{'PATH_INFO'} .
	  " you requested could not be found.\n");

close(STDOUT);
exit(0);

