#!/usr/local/bin/perl -w

#
#     FILE: yab.pl
#   AUTHOR: Michael J. Radwin
#    DESCR: Alumni Internet Directory CGI Y! Address Book redirect
#      $Id: yab,v 5.9 2003/05/15 00:20:18 mradwin Exp mradwin $
#
#   Copyright (c) 2003  Michael J. Radwin
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

use FindBin;
use lib $FindBin::Bin;
use lib "/pub/m/r/mradwin/private/lib/perl5/site_perl";

use DB_File::Lock;
use CGI;
use CGI::Carp qw(fatalsToBrowser);
use aid_util;

aid_util::cgi_die('$PATH_INFO Missing', "This URL is bogus.")
    unless defined $ENV{'PATH_INFO'};

$ENV{'PATH_INFO'} =~ s/\+/ /g;
$ENV{'PATH_INFO'} =~ s/%([A-Fa-f0-9]{2})/pack("c",hex($1))/ge;

if ($ENV{'PATH_INFO'} =~ m,/(\d+)$,)
{
    $id = $1;

    $dbmfile = aid_util::config('dbmfile');
    die "$dbmfile: $!\n" unless -r $dbmfile;

    my(%DB);
    tie(%DB, 'DB_File::Lock', $dbmfile, O_RDONLY, 0444, $DB_HASH, 'read')
	or die "$dbmfile: $!\n";

    my $val = $DB{$id};

    untie(%DB);

    if (defined $val)
    {
	my %rec = aid_util::db_unpack_rec($id,$val);

	my $url = aid_util::yahoo_abook_path(\%rec);
	$url =~ s/\&amp;/\&/g;
	print "Location: ", $url, "\015\012\015\012";

	close(STDOUT);
	exit(0);
    }
}

$ENV{'PATH_INFO'} =~ s/&/&amp;/g;
$ENV{'PATH_INFO'} =~ s/</&lt;/g;
$ENV{'PATH_INFO'} =~ s/>/&gt;/g;

print "Status: 404 Not Found\015\012";
aid_util::cgi_die('Not Found',
	  "The alumnus " . $ENV{'PATH_INFO'} .
	  " you requested could not be found.\n");

close(STDOUT);
exit(0);

